-- ===============================
-- LIMPIEZA
-- ===============================
DROP TABLE TITULACION CASCADE CONSTRAINTS;
DROP TABLE DOMINIO CASCADE CONSTRAINTS;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE COMPANIA CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS;
DROP TABLE GENERO CASCADE CONSTRAINTS;
DROP TABLE TITULO CASCADE CONSTRAINTS;
DROP TABLE IDIOMA CASCADE CONSTRAINTS;

-- ===============================
-- CREACIÓN DE TABLAS
-- ===============================

CREATE TABLE REGION (
    id_region NUMBER(2) GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 2),
    nombre_region VARCHAR2(25) NOT NULL,
    CONSTRAINT region_pk PRIMARY KEY (id_region)
);

CREATE TABLE COMUNA (
    id_comuna NUMBER(5) NOT NULL,
    comuna_nombre VARCHAR2(25) NOT NULL,
    cod_region NUMBER(2) NOT NULL,
    CONSTRAINT comuna_pk PRIMARY KEY (id_comuna, cod_region),
    CONSTRAINT comuna_fk_region FOREIGN KEY (cod_region) REFERENCES REGION(id_region)
);

CREATE TABLE COMPANIA (
    id_empresa NUMBER(2) NOT NULL,
    nombre_empresa VARCHAR2(25) NOT NULL,
    calle VARCHAR2(25),
    numeracion NUMBER(5),
    renta_promedio NUMBER(10),
    pct_aumento NUMBER(5,3),
    cod_comuna NUMBER(5),
    cod_region NUMBER(2),
    CONSTRAINT compania_pk PRIMARY KEY (id_empresa),
    CONSTRAINT compania_un_nombre UNIQUE (nombre_empresa),
    CONSTRAINT compania_fk_comuna FOREIGN KEY (cod_comuna, cod_region) REFERENCES COMUNA(id_comuna, cod_region)
);

CREATE TABLE ESTADO_CIVIL (
    id_estado_civil NUMBER(2) GENERATED ALWAYS AS IDENTITY,
    descripcion_est_civil VARCHAR2(25),
    CONSTRAINT estado_civil_pk PRIMARY KEY (id_estado_civil)
);

CREATE TABLE GENERO (
    id_genero VARCHAR2(3),
    descripcion_genero VARCHAR2(25),
    CONSTRAINT genero_pk PRIMARY KEY (id_genero)
);

CREATE TABLE TITULO (
    cod_titulo VARCHAR2(3),
    descripcion_titulo VARCHAR2(60),
    CONSTRAINT titulo_pk PRIMARY KEY (cod_titulo)
);

CREATE TABLE PERSONAL (
    rut_persona NUMBER(8),
    dv_persona CHAR(1),
    primer_nombre VARCHAR2(25),
    segundo_nombre VARCHAR2(25),
    primer_apellido VARCHAR2(25),
    segundo_apellido VARCHAR2(25),
    fecha_nacimiento DATE,
    email VARCHAR2(100),
    calle VARCHAR2(100),
    numeracion NUMBER(5),
    sueldo NUMBER(10),
    cod_comuna NUMBER(5),
    cod_region NUMBER(2),
    cod_estado_civil NUMBER(2),
    id_genero VARCHAR2(3),
    cod_empresa NUMBER(2),
    encargado_rut NUMBER(8),
    CONSTRAINT personal_pk PRIMARY KEY (rut_persona),
    CONSTRAINT personal_fk_compania FOREIGN KEY (cod_empresa) REFERENCES COMPANIA(id_empresa),
    CONSTRAINT personal_fk_comuna FOREIGN KEY (cod_comuna, cod_region) REFERENCES COMUNA(id_comuna, cod_region),
    CONSTRAINT personal_fk_estado FOREIGN KEY (cod_estado_civil) REFERENCES ESTADO_CIVIL(id_estado_civil),
    CONSTRAINT personal_fk_genero FOREIGN KEY (id_genero) REFERENCES GENERO(id_genero),
    CONSTRAINT personal_fk_encargado FOREIGN KEY (encargado_rut) REFERENCES PERSONAL(rut_persona)
);

CREATE TABLE TITULACION (
    cod_titulo VARCHAR2(3),
    persona_rut NUMBER(8),
    fecha_titulacion DATE,
    CONSTRAINT titulacion_pk PRIMARY KEY (cod_titulo, persona_rut),
    CONSTRAINT titulacion_fk_personal FOREIGN KEY (persona_rut) REFERENCES PERSONAL(rut_persona),
    CONSTRAINT titulacion_fk_titulo FOREIGN KEY (cod_titulo) REFERENCES TITULO(cod_titulo)
);

CREATE TABLE IDIOMA (
    id_idioma NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 25 INCREMENT BY 3),
    nombre_idioma VARCHAR2(30),
    CONSTRAINT idioma_pk PRIMARY KEY (id_idioma)
);

CREATE TABLE DOMINIO (
    id_idioma NUMBER(3),
    persona_rut NUMBER(8),
    descripcion VARCHAR2(25),
    CONSTRAINT dominio_pk PRIMARY KEY (id_idioma, persona_rut),
    CONSTRAINT dominio_fk_idioma FOREIGN KEY (id_idioma) REFERENCES IDIOMA(id_idioma),
    CONSTRAINT dominio_fk_personal FOREIGN KEY (persona_rut) REFERENCES PERSONAL(rut_persona)
);

-- ===============================
-- REGLAS DE NEGOCIO
-- ===============================

ALTER TABLE PERSONAL ADD CONSTRAINT un_personal_email UNIQUE (email);
ALTER TABLE PERSONAL ADD CONSTRAINT ck_personal_dv CHECK (dv_persona IN ('0','1','2','3','4','5','6','7','8','9','K'));
ALTER TABLE PERSONAL ADD CONSTRAINT ck_personal_sueldo CHECK (sueldo >= 450000);

-- ===============================
-- SECUENCIAS
-- ===============================
CREATE SEQUENCE seq_comuna START WITH 1101 INCREMENT BY 6;
CREATE SEQUENCE seq_compania START WITH 10 INCREMENT BY 5;

-- ===============================
-- INSERCIÓN DE DATOS
-- ===============================

-- REGIONES
INSERT INTO REGION (nombre_region) VALUES ('ARICA Y PARINACOTA');
INSERT INTO REGION (nombre_region) VALUES ('METROPOLITANA');
INSERT INTO REGION (nombre_region) VALUES ('LA ARAUCANIA');

-- COMUNAS
INSERT INTO COMUNA VALUES (seq_comuna.NEXTVAL, 'Arica', 7);
INSERT INTO COMUNA VALUES (seq_comuna.NEXTVAL, 'Santiago', 9);
INSERT INTO COMUNA VALUES (seq_comuna.NEXTVAL, 'Temuco', 11);

-- IDIOMAS
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Ingles');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Chino');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Aleman');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Espanol');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Frances');

-- COMPANIAS
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'CCyRojas', 'Amapolas', 506, 1857000, 0.5, 1101, 7);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'SenTTy', 'Los Alamos', 3490, 897000, 0.025, 1101, 7);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'Praxia LTDA', 'Las Camelias', 11098, 2157000, 0.035, 1107, 9);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'TIC spa', 'FLORES S.A.', 4357, 857000, NULL, 1107, 9);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'SANTANA LTDA', 'AVDA VIC. MACKENA', 106, 757000, 0.015, 1107, 9);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'FLORES Y ASOCIADOS', 'PEDRO LATORRE', 557, 589000, 0.015, 1113, 11);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'J.A. HOFFMAN', 'LATINA D.32', 509, 1857000, 0.025, 1113, 11);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'CAGLIARI D.', 'ALAMEDA', 206, 1857000, NULL, 1113, 11);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'Rojas HNOS LTDA', 'SUCRE', 106, 957000, 0.005, 1113, 11);
INSERT INTO COMPANIA VALUES (seq_compania.NEXTVAL, 'FRIENDS P. S.A', 'SUECIA', 506, 857000, 0.015, 1113, 11);

-- ===============================
-- CONSULTAS
-- ===============================

-- Informe 1
SELECT 
    nombre_empresa AS "Nombre Empresa",
    calle || ' ' || numeracion AS "Dirección",
    renta_promedio AS "Renta Promedio",
    (renta_promedio + (renta_promedio * pct_aumento)) AS "Simulación de Renta"
FROM COMPANIA
ORDER BY "Renta Promedio" DESC, "Nombre Empresa" ASC;

-- Informe 2
SELECT 
    id_empresa AS "ID Empresa",
    nombre_empresa AS "Nombre Empresa",
    renta_promedio AS "Renta Promedio Actual",
    (pct_aumento + 0.15) AS "Nuevo % Aumento",
    (renta_promedio + (renta_promedio * (pct_aumento + 0.15))) AS "Renta Promedio Incrementada"
FROM COMPANIA
ORDER BY "Renta Promedio Actual" ASC, "Nombre Empresa" DESC;
